---
- name: Configure access switches
  hosts: switches
  gather_facts: no
  tasks:
    - name: Basic global config
      ios_config:
        lines:
          - ip domain-name example.com
          - username admin privilege 15 secret mma
          - crypto key generate rsa modulus 2048
          - ip ssh version 2
        save_when: always

    - name: Enable SSH on VTY
      ios_config:
        lines:
          - line vty 0 4
          - login local
          - transport input ssh

    - name: Create VLANs 10‑60 + 80,90
      ios_vlan:
        vlan_id: "{{ item }}"
      loop: [10,20,30,40,50,60,80,90]

    - name: Configure trunk uplinks
      ios_config:
        lines:
          - interface range Ethernet0/0-1
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - no shutdown

    - name: Configure access port for specific VLAN
      vars:
        vlan_access: "{{ hostvars[inventory_hostname].vlan | default(None) }}"
      when: vlan_access is defined
      ios_config:
        lines:
          - interface Ethernet0/2
          - switchport mode access
          - switchport access vlan {{ vlan_access }}
          - no shutdown

